from __future__ import annotations

HTML = """<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="csrf-token" content="{csrf}"><title>小说抓取任务</title>
<style nonce="{nonce}">
:root{{font-family:system-ui,sans-serif;color:#18212f;background:#f4f7fb}}*{{box-sizing:border-box}}body{{margin:0}}main{{max-width:1180px;margin:auto;padding:24px}}h1{{font-size:clamp(1.5rem,4vw,2.4rem)}}h2{{font-size:1.1rem;margin:0 0 12px}}.card{{background:white;border:1px solid #dfe7f1;border-radius:8px;padding:18px;margin:14px 0;box-shadow:0 5px 20px #25405a12}}form,.row{{display:flex;gap:10px;flex-wrap:wrap;align-items:center}}input,button,select,textarea{{font:inherit;padding:10px 12px;border-radius:8px;border:1px solid #b8c6d8}}input{{flex:1;min-width:180px}}textarea{{width:100%;min-height:180px;font-family:ui-monospace,monospace;font-size:.9rem}}button{{background:#175cd3;color:white;border:0;cursor:pointer}}button.secondary{{background:#475467}}button.danger{{background:#b42318}}label{{display:flex;gap:8px;align-items:center}}label input{{min-width:auto;flex:0}}table{{width:100%;border-collapse:collapse}}th,td{{padding:9px;text-align:left;border-bottom:1px solid #edf1f6;vertical-align:top}}.origin{{font-family:ui-monospace,monospace;color:#475467}}.muted{{color:#667085}}#message{{min-height:1.5em}}@media(max-width:760px){{table,thead,tbody,tr,th,td{{display:block}}thead{{display:none}}td{{border:0;padding:4px}}tr{{border-bottom:1px solid #dfe7f1;padding:8px}}}}
</style></head>
<body><main><h1>小说抓取任务</h1><p id="message" role="status"></p>
<section class="card"><h2>合规确认</h2><label><input id="allow-third-party" type="checkbox">我确认目标内容已获授权，并遵守 robots、条款、版权许可和速率限制。</label><p class="muted">第三方线上抓取、探索和 TTS 默认禁用；本地与测试域名不需要确认。</p></section>
<section class="card"><h2>新建任务</h2><form id="create-form"><input id="source-url" type="url" required placeholder="https://example.com/book"><button>开始抓取</button></form></section>
<section class="card"><h2>新源站探索</h2><form id="explore-form"><input id="explore-url" type="url" required placeholder="https://example.com/book"><select id="explore-sample"><option value="2">2章样本</option><option value="3" selected>3章样本</option><option value="5">5章样本</option></select><button type="submit">生成探索报告</button></form><div id="exploration"></div></section>
<section class="card"><div class="row"><h2>后台任务</h2><button id="refresh-tasks" type="button">刷新</button></div><div id="tasks"></div></section>
<section class="card"><div class="row"><h2>书籍</h2><button id="refresh-books" type="button">刷新</button></div><div id="books"></div></section>
<section class="card"><div class="row"><h2>语音转换进度</h2><button id="refresh-tts" type="button">刷新</button></div><div id="tts-progress"></div></section>
</main><script nonce="{nonce}">
const csrf=document.querySelector('meta[name="csrf-token"]').content;
const message=document.getElementById('message');
const allowBox=document.getElementById('allow-third-party');
function node(tag,text,cls){{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n}}
function allowed(){{return allowBox.checked}}
async function request(path,options={{}}){{const init={{credentials:'same-origin',...options,headers:{{...(options.headers||{{}})}}}};if(init.method==='POST'){{init.headers['Content-Type']='application/json';init.headers['X-CSRF-Token']=csrf;init.body=JSON.stringify(options.body||{{}})}}const response=await fetch('/api'+path,init);const data=await response.json();if(!response.ok)throw new Error(data.error?.code||'request_failed');return data}}
function actionButton(label,path,body={{}},cls=''){{const b=node('button',label,cls);b.type='button';b.addEventListener('click',async()=>{{try{{await request(path,{{method:'POST',body}});await loadTasks()}}catch(e){{message.textContent=e.message}}}});return b}}
function bookActionButton(label,path,body,resultText,cls=''){{const b=node('button',label,cls);b.type='button';b.addEventListener('click',async()=>{{try{{const data=await request(path,{{method:'POST',body}});message.textContent=resultText;await loadBooks();return data}}catch(e){{message.textContent=e.message}}}});return b}}
function deleteBookControl(book){{const box=node('span');const begin=()=>{{const remove=node('button','删除','danger');remove.type='button';remove.addEventListener('click',confirm);box.replaceChildren(remove)}};const confirm=()=>{{const yes=bookActionButton('确认删除',`/books/${{book.id}}/delete`,{{}},'书籍已删除','danger');const no=node('button','取消删除','secondary');no.type='button';no.addEventListener('click',begin);box.replaceChildren(yes,no)}};begin();return box}}
function selectorForm(task){{const form=node('form');const fields=['title','author','chapter_list','chapter_title','content'];for(const name of fields){{const input=node('input');input.name=name;input.maxLength=1000;input.placeholder=`${{name}} selector`;form.append(input)}}const button=node('button','确认配置');button.type='submit';form.append(button);form.addEventListener('submit',async e=>{{e.preventDefault();const selector_overrides={{}};for(const input of form.querySelectorAll('input'))if(input.value)selector_overrides[input.name]=input.value;try{{await request(`/tasks/${{task.task_id}}/confirm`,{{method:'POST',body:{{selector_overrides}}}});await loadTasks()}}catch(err){{message.textContent=err.message}}}});return form}}
function showExploration(data){{const box=document.getElementById('exploration');const summary=node('p',`domain=${{data.domain}} sample_count=${{data.sample_count}} requires_dedicated_adapter=${{data.requires_dedicated_adapter}} warning_codes=${{(data.warning_codes||[]).join(',')||'-'}}`);const area=node('textarea');area.readOnly=true;area.value=JSON.stringify(data.proposed_config,null,2);box.replaceChildren(summary,area)}}
async function loadTasks(){{try{{const data=await request('/tasks');const table=node('table');for(const task of data.tasks){{const row=node('tr');row.append(node('td',task.task_id),node('td',task.status));const controls=node('td');if(task.status==='paused')controls.append(actionButton('恢复',`/tasks/${{task.task_id}}/resume`));else if(!task.terminal)controls.append(actionButton('暂停',`/tasks/${{task.task_id}}/pause`));if(!task.terminal)controls.append(actionButton('取消',`/tasks/${{task.task_id}}/cancel`,{{}},'danger'));const interaction=task.interaction||{{}};if(interaction.safe_origin)controls.append(node('p',`safe_origin：${{interaction.safe_origin}}`,'origin'));if(interaction.verification_required)controls.append(actionButton('继续验证',`/tasks/${{task.task_id}}/continue`));if(interaction.confirmation_required)controls.append(selectorForm(task));if(interaction.cleanup_required||task.cleanup_required)controls.append(actionButton('重试清理',`/tasks/${{task.task_id}}/retry-cleanup`));row.append(controls);table.append(row)}}document.getElementById('tasks').replaceChildren(table)}}catch(e){{message.textContent=e.message}}}}
async function loadBooks(){{try{{const data=await request('/books');const table=node('table');for(const book of data.books){{const row=node('tr');row.append(node('td',book.id),node('td',book.title),node('td',`${{book.done||0}}/${{book.total||0}}`));const controls=node('td');controls.append(bookActionButton('导出',`/books/${{book.id}}/export`,{{format:'txt'}},'导出已完成'));controls.append(bookActionButton('EasyVoice JSON',`/books/${{book.id}}/tts-export`,{{allow_third_party:allowed()}},'EasyVoice JSON 已导出'));controls.append(bookActionButton('转换语音',`/books/${{book.id}}/tts-convert`,{{allow_third_party:allowed(),base_url:'http://localhost:9549'}},'EasyVoice 转换已提交'));controls.append(deleteBookControl(book));row.append(controls);table.append(row)}}document.getElementById('books').replaceChildren(table)}}catch(e){{message.textContent=e.message}}}}
async function loadTtsProgress(){{try{{const data=await request('/tts/progress');const box=document.getElementById('tts-progress');if(!data.conversions.length){{box.replaceChildren(node('p','暂无转换进度','muted'));return}}const table=node('table');const head=node('tr');head.append(node('th','输出'),node('th','分组'),node('th','当前'),node('th','阶段'),node('th','最近分组'));table.append(head);for(const item of data.conversions){{const row=node('tr');const recent=(item.groups||[]).slice(-4).map(g=>`${{g.group}} ${{g.chapter_mp3}}章 ${{g.phase}}`).join(' / ');row.append(node('td',item.id),node('td',`${{item.completed_groups}}/${{item.total_groups}}`),node('td',item.current_group||'-'),node('td',item.current_phase||'-'),node('td',recent||'-'));table.append(row)}}box.replaceChildren(table)}}catch(e){{message.textContent=e.message}}}}
document.getElementById('create-form').addEventListener('submit',async e=>{{e.preventDefault();try{{await request('/tasks',{{method:'POST',body:{{url:document.getElementById('source-url').value,allow_third_party:allowed()}}}});message.textContent='任务已创建';await loadTasks()}}catch(err){{message.textContent=err.message}}}});
document.getElementById('explore-form').addEventListener('submit',async e=>{{e.preventDefault();try{{const data=await request('/explorations',{{method:'POST',body:{{url:document.getElementById('explore-url').value,sample:Number(document.getElementById('explore-sample').value),allow_third_party:allowed()}}}});message.textContent='探索报告已生成';showExploration(data)}}catch(err){{message.textContent=err.message}}}});
document.getElementById('refresh-tasks').addEventListener('click',loadTasks);document.getElementById('refresh-books').addEventListener('click',loadBooks);document.getElementById('refresh-tts').addEventListener('click',loadTtsProgress);loadTasks();loadBooks();loadTtsProgress();setInterval(loadTasks,5000);setInterval(loadTtsProgress,10000);
</script></body></html>"""

__all__ = ["HTML"]
