from __future__ import annotations

HTML = """<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="csrf-token" content="{csrf}"><title>小说抓取任务</title>
<style nonce="{nonce}">:root{{font-family:system-ui,sans-serif;color:#18212f;background:#f4f7fb}}*{{box-sizing:border-box}}body{{margin:0}}main{{max-width:1100px;margin:auto;padding:24px}}h1{{font-size:clamp(1.5rem,4vw,2.4rem)}}.card{{background:white;border:1px solid #dfe7f1;border-radius:14px;padding:18px;margin:14px 0;box-shadow:0 5px 20px #25405a12}}form,.row{{display:flex;gap:10px;flex-wrap:wrap;align-items:center}}input,button,select{{font:inherit;padding:10px 12px;border-radius:8px;border:1px solid #b8c6d8}}input{{flex:1;min-width:180px}}button{{background:#175cd3;color:white;border:0;cursor:pointer}}button.danger{{background:#b42318}}table{{width:100%;border-collapse:collapse}}th,td{{padding:9px;text-align:left;border-bottom:1px solid #edf1f6}}.origin{{font-family:ui-monospace,monospace;color:#475467}}#message{{min-height:1.5em}}@media(max-width:680px){{table,thead,tbody,tr,th,td{{display:block}}thead{{display:none}}td{{border:0;padding:4px}}tr{{border-bottom:1px solid #dfe7f1;padding:8px}}}}</style></head>
<body><main><h1>小说抓取任务</h1><p id="message" role="status"></p>
<section class="card"><h2>新建任务</h2><form id="create-form"><input id="source-url" type="url" required placeholder="https://example.com/book"><button>开始抓取</button></form></section>
<section class="card"><div class="row"><h2>后台任务</h2><button id="refresh-tasks" type="button">刷新</button></div><div id="tasks"></div></section>
<section class="card"><div class="row"><h2>书籍</h2><button id="refresh-books" type="button">刷新</button></div><div id="books"></div></section>
</main><script nonce="{nonce}">
const csrf=document.querySelector('meta[name="csrf-token"]').content;
const message=document.getElementById('message');
function node(tag,text,cls){{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n}}
async function request(path,options={{}}){{const init={{credentials:'same-origin',...options,headers:{{...(options.headers||{{}})}}}};if(init.method==='POST'){{init.headers['Content-Type']='application/json';init.headers['X-CSRF-Token']=csrf;init.body=JSON.stringify(options.body||{{}})}}const response=await fetch('/api'+path,init);const data=await response.json();if(!response.ok)throw new Error(data.error?.code||'request_failed');return data}}
function actionButton(label,path,body={{}},cls=''){{const b=node('button',label,cls);b.type='button';b.addEventListener('click',async()=>{{try{{await request(path,{{method:'POST',body}});await loadTasks()}}catch(e){{message.textContent=e.message}}}});return b}}
function selectorForm(task){{const form=node('form');const fields=['title','author','chapter_list','chapter_title','content'];for(const name of fields){{const input=node('input');input.name=name;input.maxLength=1000;input.placeholder=`${{name}} selector`;form.append(input)}}const button=node('button','确认配置');button.type='submit';form.append(button);form.addEventListener('submit',async e=>{{e.preventDefault();const selector_overrides={{}};for(const input of form.querySelectorAll('input'))if(input.value)selector_overrides[input.name]=input.value;try{{await request(`/tasks/${{task.task_id}}/confirm`,{{method:'POST',body:{{selector_overrides}}}});await loadTasks()}}catch(err){{message.textContent=err.message}}}});return form}}
async function loadTasks(){{try{{const data=await request('/tasks');const table=node('table');for(const task of data.tasks){{const row=node('tr');row.append(node('td',task.task_id),node('td',task.status));const controls=node('td');if(task.status==='paused')controls.append(actionButton('恢复',`/tasks/${{task.task_id}}/resume`));else if(!task.terminal)controls.append(actionButton('暂停',`/tasks/${{task.task_id}}/pause`));if(!task.terminal)controls.append(actionButton('取消',`/tasks/${{task.task_id}}/cancel`,{{}},'danger'));const interaction=task.interaction||{{}};if(interaction.safe_origin)controls.append(node('p',`来源：${{interaction.safe_origin}}`,'origin'));if(interaction.verification_required)controls.append(actionButton('继续验证',`/tasks/${{task.task_id}}/continue`));if(interaction.confirmation_required)controls.append(selectorForm(task));if(interaction.cleanup_required||task.cleanup_required)controls.append(actionButton('重试清理',`/tasks/${{task.task_id}}/retry-cleanup`));row.append(controls);table.append(row)}}document.getElementById('tasks').replaceChildren(table)}}catch(e){{message.textContent=e.message}}}}
async function loadBooks(){{try{{const data=await request('/books');const table=node('table');for(const book of data.books){{const row=node('tr');row.append(node('td',book.id),node('td',book.title),node('td',`${{book.done||0}}/${{book.total||0}}`));const controls=node('td');controls.append(actionButton('导出',`/books/${{book.id}}/export`,{{format:'txt'}}),actionButton('删除',`/books/${{book.id}}/delete`,{{}},'danger'));row.append(controls);table.append(row)}}document.getElementById('books').replaceChildren(table)}}catch(e){{message.textContent=e.message}}}}
document.getElementById('create-form').addEventListener('submit',async e=>{{e.preventDefault();try{{await request('/tasks',{{method:'POST',body:{{url:document.getElementById('source-url').value}}}});message.textContent='任务已创建';await loadTasks()}}catch(err){{message.textContent=err.message}}}});
document.getElementById('refresh-tasks').addEventListener('click',loadTasks);document.getElementById('refresh-books').addEventListener('click',loadBooks);loadTasks();loadBooks();setInterval(loadTasks,5000);
</script></body></html>"""

__all__ = ["HTML"]
